rewrite: mtfwiki guidelines
project-trans/workflow pull request #1
Opened 2023-08-22 10:44 UTC by septs

2023-08-22 11:06 UTC, CoelacanthusHex commented on mtf-wiki.zh.md
> +医疗资源（Psycho、HRT）：[@septs]、[@saeziae]
我可以负担一部分精神科及 HRT 医疗资源审阅任务

2023-08-22 11:06 UTC, CoelacanthusHex commented on mtf-wiki.zh.md
>  ### 问题
感觉问题这个名字不好，可以跟随 GitHub 官方翻译叫议题。

2023-08-22 11:06 UTC, CoelacanthusHex commented on mtf-wiki.zh.md
> +封闭式问题如果过于简陋、缺乏可信度可维持打开状态并标注相关情况。
感觉简陋用得不好，改成
```suggestion
封闭式问题如果缺乏关键信息或者缺乏可信度可维持打开状态并标注相关情况。
```

2023-08-25 15:58 UTC, Cryolitia requested changes

2023-08-25 15:58 UTC, Cryolitia commented on mtf-wiki.zh.md
> +医疗资源（Psycho、HRT）：[@septs]、[@saeziae]、[@CoelacanthusHex]
```suggestion
医疗资源（Psycho、HRT）：[@septs]、[@saeziae]、[@CoelacanthusHex]、[@Cryolitia ]
```

2023-08-25 16:20 UTC, Cryolitia approved these changes

2023-08-27 04:31 UTC, CoelacanthusHex approved these changes
LGTM

2023-08-27 08:09 UTC, saeziae approved these changes

2023-08-27 08:37 UTC, merged